database:
  host: mysql.clarksonmsda.org
  port: 3306
  user: srinatr
  password: 7CLs7jxjQu5VG3T
  name: srinatr_monitor2
  charset: utf8mb4

auth:
  header: Authorization
  prefix: "Bearer "

flask:
  host: 0.0.0.0
  port: 5000
  debug: true
